CREATE TABLE expenses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description TEXT,
    date TIMESTAMP NOT NULL DEFAULT now(),
    amount DECIMAL(19,4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    modified_at TIMESTAMP NOT NULL DEFAULT now(),
    category INTEGER REFERENCES categories(id) NOT NULL
);